
[font]
size = 18
normal = { family = "MesloLGS Nerd Font Mono", style = "Regular" }
bold = { family = "MesloLGS Nerd Font Mono", style = "Bold" }
italic = { family = "MesloLGS Nerd Font Mono", style = "Italic" }
bold_italic = { family = "MesloLGS Nerd Font Mono", style = "Bold Italic" }

[window]
startup_mode = "Maximized"
decorations = "buttonless"
opacity = 0.7
blur = true

[general]
import = ["~/.config/alacritty/themes/gruvbox_dark.toml"]
