import = ["~/.config/alacritty/themes/gruvbox_dark.toml"]

[font]
size = 14
normal = { family = "MesloLGS NF", style = "Regular" }
bold = { family = "MesloLGS NF", style = "Bold" }
italic = { family = "MesloLGS NF", style = "Italic" }
bold_italic = { family = "MesloLGS NF", style = "Bold Italic" }

[window]
decorations = "buttonless"
opacity = 0.7
blur = true
padding = { x = 2, y = 2 }
